### ISSUE TITLE
wrong language statistics

### ISSUE THREAD

**Issue by thorade** [jonas/dgrep#1]
I came here, because your repo is listed as one of the trending repositories written mainly in Modelica:
https://github.com/trending?l=modelica
This is because some of your test files have the extension `.mo` and the [github linguist](https://github.com/github/linguist) thinks these are Modelica files. 

If you want to fix the language statistics, the easiest way would be to exclude the folder `src/test/resources` from the language statistics using the `.gitattributes` as described here:
https://github.com/github/linguist#using-gitattributes

The content of your `.gitattributes` would then have to be:

```
src/test/resources/* linguist-vendored
```

or

```
src/test/resources/* linguist-documentation
```

**Comment by jonas** [comment]
As indicated the files were copied from the twitter/effectivescala repo and the extension kept. Anyway, this should be fixed now.

**Comment by thorade** [comment]
Thanks for fixing this, and yes, you were already giving the information elsewhere.
